from typing import List, Optional

from pydantic import BaseModel, Field

from app.core.expression_engine.validator import ValidationResult


class AlphaIdeaRequest(BaseModel):
    user_prompt: str = Field(
        ..., min_length=3, description="Natural-language alpha idea description."
    )
    preferred_style: Optional[str] = Field(
        default="balanced",
        description="Alpha generation tone/style style: 'balanced', 'conservative', or 'aggressive'.",
    )


class AlphaIdea(BaseModel):
    title: str = Field(..., description="Short title of the alpha idea.")
    hypothesis: str = Field(..., description="Economic or financial hypothesis behind the idea.")
    formula: str = Field(..., description="Mathematical alpha expression.")
    required_columns: List[str] = Field(
        ..., description="List of columns referenced in the formula."
    )
    expected_behavior: str = Field(..., description="Expected performance or behavior description.")
    risk_notes: List[str] = Field(..., description="Key risk considerations for this strategy.")
    explanation: str = Field(..., description="Detailed explanation of the formula and logic.")
    tags: List[str] = Field(..., description="Metadata tags for categorization.")


class AlphaIdeaResponse(BaseModel):
    idea: AlphaIdea = Field(
        ..., description="Structured alpha idea details generated by the agent."
    )
    validation: ValidationResult = Field(..., description="Formula validation details.")
    warnings: List[str] = Field(
        ..., description="Workspace warnings about safety, simplification, or mock limits."
    )
